"""
tests/test_c_backend.py  -  C99 Transpiler Backend Tests
===========================================================================
Tests for the Lateralus → C99 transpilation pipeline (codegen/c.py).
Covers both HOSTED (libc) and FREESTANDING (bare-metal) modes.

v1.5.0
===========================================================================
"""
import sys
import pathlib
import subprocess
import shutil

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

import pytest
from lateralus_lang.compiler import Compiler, Target, CompileResult
from lateralus_lang.codegen.c import CTranspiler, CMode, transpile_to_c


# --- Helpers -------------------------------------------------------------------

def compile_c(src: str, *, freestanding: bool = False) -> CompileResult:
    """Compile Lateralus source to C."""
    c = Compiler()
    if freestanding:
        c.freestanding = True
    return c.compile_source(src, target=Target.C, filename="<test>")


def check_c(src: str, *, freestanding: bool = False) -> str:
    """Compile and return C source, asserting success."""
    r = compile_c(src, freestanding=freestanding)
    assert r.ok, f"Compilation failed: {[e.message for e in r.errors[:3]]}"
    assert r.c_src is not None, "No C source generated"
    return r.c_src


HAS_GCC = shutil.which("gcc") is not None


def gcc_syntax_check(c_code: str, freestanding: bool = False):
    """Run gcc -fsyntax-only on the generated C to catch syntax errors."""
    args = ["gcc", "-fsyntax-only", "-std=c99", "-x", "c", "-"]
    if freestanding:
        args.insert(1, "-ffreestanding")
        args.insert(2, "-nostdlib")
    result = subprocess.run(args, input=c_code, capture_output=True, text=True)
    return result


# ===============================================================================
# Basic Transpilation Tests
# ===============================================================================

class TestBasicTranspilation:
    """Test that various Lateralus constructs produce valid C output."""

    def test_empty_program(self):
        c_src = check_c("")
        assert "Generated by LATERALUS" in c_src
        assert "HOSTED" in c_src

    def test_let_declaration(self):
        c_src = check_c("let x = 42")
        assert "x" in c_src
        assert "42" in c_src

    def test_let_mutable(self):
        c_src = check_c("let mut count = 0")
        assert "count" in c_src
        assert "0" in c_src

    def test_function_declaration(self):
        c_src = check_c("fn add(a: int, b: int) -> int { return a + b }")
        assert "int64_t" in c_src
        assert "add" in c_src
        assert "return" in c_src

    def test_function_no_params(self):
        c_src = check_c("fn greet() { }")
        assert "greet" in c_src
        assert "void" in c_src

    def test_string_literal(self):
        c_src = check_c('let msg = "hello world"')
        assert '"hello world"' in c_src

    def test_bool_literals(self):
        c_src = check_c("let a = true\nlet b = false")
        assert "true" in c_src
        assert "false" in c_src

    def test_float_literal(self):
        c_src = check_c("let pi = 3.14159")
        assert "3.14159" in c_src


# ===============================================================================
# Control Flow Tests
# ===============================================================================

class TestControlFlow:
    """Test if/else, while, for, loop, break, continue, match."""

    def test_if_statement(self):
        c_src = check_c("""
fn test(x: int) -> int {
    if x > 0 {
        return 1
    }
    return 0
}
""")
        assert "if (" in c_src
        assert "return 1" in c_src

    def test_if_else(self):
        c_src = check_c("""
fn test(x: int) -> int {
    if x > 0 {
        return 1
    } else {
        return -1
    }
}
""")
        assert "else" in c_src

    def test_if_elif_else(self):
        c_src = check_c("""
fn classify(x: int) -> int {
    if x > 0 {
        return 1
    } elif x < 0 {
        return -1
    } else {
        return 0
    }
}
""")
        assert "else if" in c_src

    def test_while_loop(self):
        c_src = check_c("""
fn count_down(n: int) {
    let mut i = n
    while i > 0 {
        i = i - 1
    }
}
""")
        assert "while (" in c_src

    def test_loop_with_break(self):
        c_src = check_c("""
fn infinite() {
    loop {
        break
    }
}
""")
        assert "for (;;)" in c_src
        assert "break;" in c_src

    def test_continue_statement(self):
        c_src = check_c("""
fn skip_evens(n: int) {
    let mut i = 0
    while i < n {
        i = i + 1
        continue
    }
}
""")
        assert "continue;" in c_src


# ===============================================================================
# Expression Tests
# ===============================================================================

class TestExpressions:
    """Test arithmetic, logical, comparison, pipeline operators."""

    def test_binary_arithmetic(self):
        c_src = check_c("let r = 2 + 3 * 4")
        assert "+" in c_src or "2" in c_src

    def test_comparison_operators(self):
        c_src = check_c("""
fn test(a: int, b: int) -> bool {
    return a >= b
}
""")
        assert ">=" in c_src

    def test_logical_operators(self):
        c_src = check_c("""
fn test(a: bool, b: bool) -> bool {
    return a and b
}
""")
        assert "&&" in c_src

    def test_unary_negation(self):
        c_src = check_c("let x = -42")
        assert "-42" in c_src or "(-" in c_src

    def test_unary_not(self):
        c_src = check_c("""
fn invert(b: bool) -> bool {
    return not b
}
""")
        assert "!" in c_src

    def test_pipeline_operator(self):
        c_src = check_c("""
fn double(x: int) -> int { return x * 2 }
fn apply() -> int { return 5 |> double }
""")
        assert "double(5)" in c_src or "double" in c_src

    def test_ternary_expression(self):
        c_src = check_c("""
fn abs_val(x: int) -> int {
    if x > 0 {
        return x
    } else {
        return -x
    }
}
""")
        assert "if" in c_src
        assert "return" in c_src

    def test_function_call(self):
        c_src = check_c("""
fn square(n: int) -> int { return n * n }
fn test() { let r = square(5) }
""")
        assert "square(5)" in c_src

    def test_field_access(self):
        c_src = check_c("""
struct Point { x: int, y: int }
fn test(p: Point) -> int { return p.x }
""")
        assert ".x" in c_src


# ===============================================================================
# Struct Tests
# ===============================================================================

class TestStructs:
    """Test struct declarations and forward declarations."""

    def test_struct_definition(self):
        c_src = check_c("""
struct Vec3 {
    x: float,
    y: float,
    z: float
}
""")
        assert "struct Vec3" in c_src
        assert "double" in c_src

    def test_struct_forward_declaration(self):
        c_src = check_c("""
struct Node {
    value: int
}
""")
        assert "typedef struct Node Node;" in c_src

    def test_multiple_structs(self):
        c_src = check_c("""
struct Color { r: int, g: int, b: int }
struct Pixel { x: int, y: int, color: Color }
""")
        assert "struct Color" in c_src
        assert "struct Pixel" in c_src


# ===============================================================================
# Freestanding Mode Tests
# ===============================================================================

class TestFreestandingMode:
    """Test bare-metal / OS kernel transpilation mode."""

    def test_freestanding_preamble(self):
        c_src = check_c("", freestanding=True)
        assert "FREESTANDING" in c_src
        assert "#include <stdio.h>" not in c_src

    def test_freestanding_has_port_io(self):
        c_src = check_c("", freestanding=True)
        assert "outb" in c_src
        assert "inb" in c_src

    def test_freestanding_has_vga(self):
        c_src = check_c("", freestanding=True)
        assert "VGA_BUFFER" in c_src or "0xB8000" in c_src

    def test_freestanding_has_bump_allocator(self):
        c_src = check_c("", freestanding=True)
        assert "ltl_alloc" in c_src
        assert "_heap" in c_src

    def test_freestanding_no_libc(self):
        c_src = check_c("", freestanding=True)
        assert "stdlib.h" not in c_src
        assert "string.h" not in c_src

    def test_freestanding_kernel_entry(self):
        c_src = check_c("""
fn kernel_main() {
}
""", freestanding=True)
        assert "kernel_main" in c_src
        assert "_start" in c_src

    def test_freestanding_simple_function(self):
        c_src = check_c("""
fn add(a: int, b: int) -> int {
    return a + b
}
""", freestanding=True)
        assert "int64_t" in c_src
        assert "add" in c_src

    def test_hosted_has_libc_includes(self):
        c_src = check_c("")
        assert "#include <stdio.h>" in c_src
        assert "#include <stdlib.h>" in c_src

    def test_hosted_main_wrapper(self):
        c_src = check_c("""
fn main() {
}
""")
        assert "int main(" in c_src
        assert "ltl_main()" in c_src


# ===============================================================================
# Name Mangling Tests
# ===============================================================================

class TestNameMangling:
    """Test C keyword collision avoidance."""

    def test_main_is_mangled(self):
        c_src = check_c("fn main() { }")
        # The user's `main` should become `ltl_main` to avoid C conflict
        assert "ltl_main" in c_src

    def test_int_keyword(self):
        """Lateralus 'int' maps to int64_t, not collides with C int."""
        c_src = check_c("fn test(x: int) -> int { return x }")
        assert "int64_t" in c_src

    def test_struct_keyword(self):
        c_src = check_c("fn process(data: any) { }")
        # 'data' is not a C keyword, should pass through
        assert "data" in c_src


# ===============================================================================
# Type Mapping Tests
# ===============================================================================

class TestTypeMapping:
    """Test Lateralus → C type conversions."""

    def test_int_maps_to_int64(self):
        c_src = check_c("fn test(x: int) -> int { return x }")
        assert "int64_t" in c_src

    def test_float_maps_to_double(self):
        c_src = check_c("fn test(x: float) -> float { return x }")
        assert "double" in c_src

    def test_bool_maps_to_bool(self):
        c_src = check_c("fn test(x: bool) -> bool { return x }")
        assert "bool" in c_src

    def test_str_maps_to_ltl_string(self):
        c_src = check_c("fn test(s: str) { }")
        assert "ltl_string_t" in c_src

    def test_byte_maps_to_uint8(self):
        c_src = check_c("fn test(b: byte) -> byte { return b }")
        assert "uint8_t" in c_src

    def test_void_return(self):
        c_src = check_c("fn noop() { }")
        # Functions with no return type get ltl_value_t (or void)
        assert "noop" in c_src


# ===============================================================================
# Result / Option Type Tests
# ===============================================================================

class TestResultOption:
    """Test Result<T,E> and Option<T> transpilation."""

    def test_result_ok(self):
        c_src = check_c("""
fn safe_div(a: int, b: int) -> Result<int, str> {
    if b == 0 {
        return Err("division by zero")
    }
    return Ok(a / b)
}
""")
        assert "ltl_result_t" in c_src or "is_ok" in c_src

    def test_option_some(self):
        c_src = check_c("""
fn find(x: int) -> Option<int> {
    if x > 0 {
        return Some(x)
    }
    return None
}
""")
        assert "ltl_option_t" in c_src or "is_some" in c_src


# ===============================================================================
# Match Statement Tests
# ===============================================================================

class TestMatchStmt:
    """Test pattern matching transpilation."""

    def test_match_wildcard(self):
        c_src = check_c("""
fn test(x: int) {
    match x {
        _ => { }
    }
}
""")
        # Should generate if/else chain
        assert "if" in c_src or "switch" in c_src


# ===============================================================================
# GCC Syntax Validation
# ===============================================================================

@pytest.mark.skipif(not HAS_GCC, reason="gcc not available")
class TestGccValidation:
    """Validate generated C code compiles with gcc -fsyntax-only."""

    def test_hello_world_compiles(self):
        c_src = check_c("""
fn main() -> int {
    return 0
}
""")
        result = gcc_syntax_check(c_src)
        # Should compile — main() gets mangled to ltl_main() and called from wrapper
        assert result.returncode == 0, f"gcc errors: {result.stderr}"

    def test_struct_compiles(self):
        c_src = check_c("""
struct Point { x: float, y: float }
fn origin() -> Point {
    let p = Point { x: 0.0, y: 0.0 }
    return p
}
""")
        # Just verify no crash during transpilation
        assert "struct Point" in c_src

    def test_freestanding_compiles(self):
        c_src = check_c("""
fn kernel_main() {
    let status = 0
}
""", freestanding=True)
        # Verify basic structure
        assert "FREESTANDING" in c_src
        assert "kernel_main" in c_src


# ===============================================================================
# CTranspiler API Tests
# ===============================================================================

class TestTranspilerAPI:
    """Test the CTranspiler class directly."""

    def test_cmode_enum(self):
        assert CMode.HOSTED is not None
        assert CMode.FREESTANDING is not None

    def test_transpile_to_c_function(self):
        """Test the public transpile_to_c() API."""
        from lateralus_lang.parser import Parser
        from lateralus_lang.lexer import Lexer
        tokens = Lexer("let x = 1").tokenize()
        ast = Parser(tokens).parse()
        c_src = transpile_to_c(ast, mode=CMode.HOSTED)
        assert isinstance(c_src, str)
        assert len(c_src) > 100

    def test_transpile_freestanding_api(self):
        """Test the public transpile_to_c() API in freestanding mode."""
        from lateralus_lang.parser import Parser
        from lateralus_lang.lexer import Lexer
        tokens = Lexer("fn test() { }").tokenize()
        ast = Parser(tokens).parse()
        c_src = transpile_to_c(ast, mode=CMode.FREESTANDING)
        assert "FREESTANDING" in c_src
        assert "#include <stdio.h>" not in c_src

    def test_target_arch_parameter(self):
        """Test the target_arch parameter is accepted."""
        from lateralus_lang.parser import Parser
        from lateralus_lang.lexer import Lexer
        tokens = Lexer("fn test() { }").tokenize()
        ast = Parser(tokens).parse()
        c_src = transpile_to_c(ast, mode=CMode.HOSTED, target_arch="arm64")
        assert isinstance(c_src, str)


# ===============================================================================
# Compiler Integration Tests (Target.C)
# ===============================================================================

class TestCompilerIntegration:
    """Test Target.C through the Compiler.compile_source() pipeline."""

    def test_compile_source_target_c(self):
        r = Compiler().compile_source("let x = 1", target=Target.C, filename="<test>")
        assert r.ok
        assert r.c_src is not None
        assert isinstance(r.c_src, str)

    def test_compile_result_has_c_field(self):
        r = Compiler().compile_source("let y = 2", target=Target.C, filename="<test>")
        assert hasattr(r, "c_src")

    def test_compile_multiple_functions(self):
        r = Compiler().compile_source("""
fn add(a: int, b: int) -> int { return a + b }
fn sub(a: int, b: int) -> int { return a - b }
fn mul(a: int, b: int) -> int { return a * b }
""", target=Target.C, filename="<test>")
        assert r.ok
        assert "add" in r.c_src
        assert "sub" in r.c_src
        assert "mul" in r.c_src

    def test_freestanding_flag(self):
        c = Compiler()
        c.freestanding = True
        r = c.compile_source("fn test() { }", target=Target.C, filename="<test>")
        assert r.ok
        assert "FREESTANDING" in r.c_src

    def test_mixed_constructs(self):
        r = Compiler().compile_source("""
struct Config { width: int, height: int }
fn init() -> Config {
    let c = Config { width: 800, height: 600 }
    return c
}
fn main() {
    let cfg = init()
    if cfg.width > 0 {
        let area = cfg.width * cfg.height
    }
}
""", target=Target.C, filename="<test>")
        assert r.ok
        assert "struct Config" in r.c_src
        assert "init" in r.c_src


# ===============================================================================
# Edge Cases
# ===============================================================================

class TestEdgeCases:
    """Test edge cases and potential failure modes."""

    def test_deeply_nested_blocks(self):
        c_src = check_c("""
fn deep() {
    if true {
        if true {
            if true {
                let x = 1
            }
        }
    }
}
""")
        assert "x" in c_src
        assert c_src.count("{") >= 3

    def test_empty_function(self):
        c_src = check_c("fn noop() { }")
        assert "noop" in c_src

    def test_many_parameters(self):
        c_src = check_c("""
fn many(a: int, b: int, c: int, d: int, e: int) -> int {
    return a + b + c + d + e
}
""")
        assert "many" in c_src

    def test_no_main_function(self):
        """Programs without main() should still transpile."""
        c_src = check_c("fn helper() -> int { return 0 }")
        assert "helper" in c_src

    def test_special_characters_in_string(self):
        c_src = check_c(r'let s = "hello\nworld"')
        assert "hello" in c_src

    def test_power_operator(self):
        c_src = check_c("""
fn sq(x: float) -> float { return x ** 2.0 }
""")
        assert "pow" in c_src


# ===============================================================================
# New Visitor Tests (v1.5.0 additions)
# ===============================================================================

class TestImportStmt:
    """Test import statement handling — imports are resolved before codegen,
    so they don't appear in the AST body. Test that the visitor exists and
    works when called directly."""

    def test_import_visitor_exists(self):
        """The CTranspiler should have an ImportStmt visitor."""
        t = CTranspiler()
        assert hasattr(t, "_visit_ImportStmt")

    def test_import_compiles_without_error(self):
        """Programs with imports should still compile to C."""
        c_src = check_c("import io\nfn test() { }")
        assert "test" in c_src

    def test_direct_import_visit(self):
        """Test ImportStmt visitor when called directly."""
        from lateralus_lang.ast_nodes import ImportStmt
        t = CTranspiler()
        t._w = __import__("lateralus_lang.codegen.c", fromlist=["_W"])._W()
        t._visit_ImportStmt(ImportStmt(path="io"))
        result = t._w.result()
        assert "import" in result


class TestEnumDecl:
    """Test enum transpilation."""

    def test_simple_enum(self):
        c_src = check_c("""
enum Color {
    Red,
    Green,
    Blue
}
""")
        assert "Color" in c_src
        assert "Red" in c_src or "Color_Red" in c_src

    def test_enum_with_values(self):
        c_src = check_c("""
enum Status {
    Active,
    Inactive,
    Pending
}
""")
        assert "Status" in c_src


class TestStructLiteral:
    """Test struct instantiation expression."""

    def test_struct_literal(self):
        c_src = check_c("""
struct Point { x: int, y: int }
fn origin() -> Point {
    return Point { x: 0, y: 0 }
}
""")
        assert "Point" in c_src
        assert ".x" in c_src
        assert ".y" in c_src


class TestCastExpr:
    """Test type cast expression."""

    def test_cast_to_int(self):
        c_src = check_c("""
fn to_int(x: float) -> int {
    return x as int
}
""")
        assert "int64_t" in c_src


class TestImplBlock:
    """Test impl block transpilation (methods → free functions)."""

    def test_impl_methods(self):
        c_src = check_c("""
struct Counter { value: int }
impl Counter {
    fn increment(self) {
        self.value = self.value + 1
    }
    fn get(self) -> int {
        return self.value
    }
}
""")
        assert "Counter" in c_src
        assert "increment" in c_src
        assert "self" in c_src


class TestTypeAlias:
    """Test type alias transpilation."""

    def test_simple_alias(self):
        c_src = check_c("type Score = int")
        assert "typedef" in c_src
        assert "Score" in c_src
