#!/usr/bin/env python3
"""
tools/gen_grug_corpus.py — compile apps/grug_training/*.txt into a C header
consumed by gui/terminal.c so grugbot420 can load expanded training data.

Inputs:
    apps/grug_training/wisdom.txt   — one grug-wisdom line per entry
    apps/grug_training/jokes.txt    — one joke per entry
    apps/grug_training/smoke.txt    — one smoke-break vibe per entry
    apps/grug_training/rules.txt    — keyword[,keyword...]=>response

Output:
    gui/grug_corpus.h   (auto-generated; do not edit by hand)
"""
import os, sys, pathlib, datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
TRAIN = ROOT / "apps" / "grug_training"
OUT   = ROOT / "gui" / "grug_corpus.h"

def read_lines(path):
    if not path.exists():
        return []
    out = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        s = raw.strip()
        if not s or s.startswith("#"):
            continue
        out.append(s)
    return out

def c_escape(s):
    # Keep the header readable; escape only what C string literals require.
    return (s.replace("\\", "\\\\")
             .replace("\"", "\\\"")
             .replace("\n", "\\n")
             .replace("\t", "\\t"))

def emit_array(fh, name, items):
    fh.write(f"static const char *const {name}[] = {{\n")
    for s in items:
        fh.write(f"    \"{c_escape(s)}\",\n")
    fh.write("};\n")
    fh.write(f"static const int {name}_N = (int)(sizeof({name})/sizeof({name}[0]));\n\n")

def parse_rules(path):
    rules = []  # list of (keywords[list], response)
    for line in read_lines(path):
        if "=>" not in line:
            continue
        kw, _, resp = line.partition("=>")
        kws = [k.strip().lower() for k in kw.split(",") if k.strip()]
        resp = resp.strip()
        if kws and resp:
            rules.append((kws, resp))
    return rules

def main():
    wisdom = read_lines(TRAIN / "wisdom.txt")
    jokes  = read_lines(TRAIN / "jokes.txt")
    smoke  = read_lines(TRAIN / "smoke.txt")
    rules  = parse_rules(TRAIN / "rules.txt")

    total = len(wisdom) + len(jokes) + len(smoke) + sum(len(r[0]) for r in rules) + len(rules)

    stamp = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as fh:
        fh.write("/* AUTOGENERATED by tools/gen_grug_corpus.py — do not edit. */\n")
        fh.write(f"/* generated: {stamp} */\n")
        fh.write("#ifndef LATERALUS_GRUG_CORPUS_H\n")
        fh.write("#define LATERALUS_GRUG_CORPUS_H\n\n")

        emit_array(fh, "GRUG_WISDOM", wisdom)
        emit_array(fh, "GRUG_JOKES",  jokes)
        emit_array(fh, "GRUG_SMOKE",  smoke)

        fh.write("typedef struct {\n")
        fh.write("    const char *const *keywords;  /* NULL-terminated */\n")
        fh.write("    const char *response;\n")
        fh.write("} GrugRule;\n\n")

        for i, (kws, resp) in enumerate(rules):
            fh.write(f"static const char *const GRUG_RULE_KW_{i}[] = {{")
            fh.write(", ".join(f"\"{c_escape(k)}\"" for k in kws))
            fh.write(", (const char*)0 };\n")

        fh.write("\nstatic const GrugRule GRUG_RULES[] = {\n")
        for i, (_, resp) in enumerate(rules):
            fh.write(f"    {{ GRUG_RULE_KW_{i}, \"{c_escape(resp)}\" }},\n")
        fh.write("};\n")
        fh.write("static const int GRUG_RULES_N = (int)(sizeof(GRUG_RULES)/sizeof(GRUG_RULES[0]));\n\n")

        fh.write(f"#define GRUG_TRAINING_WISDOM_N  {len(wisdom)}\n")
        fh.write(f"#define GRUG_TRAINING_JOKES_N   {len(jokes)}\n")
        fh.write(f"#define GRUG_TRAINING_SMOKE_N   {len(smoke)}\n")
        fh.write(f"#define GRUG_TRAINING_RULES_N   {len(rules)}\n")
        fh.write(f"#define GRUG_TRAINING_TOTAL     {total}\n\n")

        fh.write("#endif /* LATERALUS_GRUG_CORPUS_H */\n")

    print(f"[grug-corpus] {OUT.relative_to(ROOT)}: "
          f"{len(wisdom)} wisdom, {len(jokes)} jokes, {len(smoke)} smoke, "
          f"{len(rules)} rules  (total tokens: {total})")

if __name__ == "__main__":
    main()
