#!/usr/bin/env python3
"""Render 'LBC Format Deep Dive' (extended reference) in canonical style."""
from pathlib import Path
from _lateralus_template import render_paper

OUT = Path(__file__).resolve().parents[1] / "pdf" / "lateralus-bytecode-format-lbc.pdf"

render_paper(
    out_path=str(OUT),
    title="LBC Format Deep Dive",
    subtitle="Instruction encoding details, optimizer hints, and the debug information schema",
    meta="bad-antics &middot; May 2025 &middot; Lateralus Language Research",
    abstract=(
        "This paper is an extended reference for the Lateralus Bytecode (LBC) format "
        "that covers aspects not addressed in the introductory LBC paper: optimizer "
        "hint annotations embedded in the bytecode, the type annotation section used "
        "by the JIT compiler, the debug information schema, and the binary patch "
        "format for hot-swap updates. It assumes familiarity with the LBC fundamentals "
        "document and is intended as a reference for compiler and runtime implementers."
    ),
    sections=[
        ("1. Optimizer Hint Annotations", [
            "LBC functions carry optimizer hint annotations in a dedicated section "
            "that precedes the instruction stream. The JIT compiler reads these "
            "hints before compiling a function. Hints are not required; their "
            "absence causes the JIT to use conservative defaults.",
            ("code",
             "// Hint section layout (per function)\n"
             "hint_count: u16\n"
             "hints: [HintRecord; hint_count]\n\n"
             "HintRecord {\n"
             "    hint_type: u8,\n"
             "    instr_offset: u16,  // instruction this hint applies to\n"
             "    value: u32,         // hint-type-specific value\n"
             "}"),
            "Defined hint types:",
            ("code",
             "0x01  LIKELY_HOT       instr is on the hot path (branch prediction)\n"
             "0x02  LIKELY_COLD      instr is rarely executed\n"
             "0x03  PURE             function call has no side effects, safe to CSE\n"
             "0x04  NO_ALIAS         two memory ops do not alias\n"
             "0x05  PIPELINE_FUSABLE stage can be fused with adjacent stage\n"
             "0x06  UNROLL_COUNT     loop unroll factor hint (value = count)"),
        ]),
        ("2. The JIT Type Annotation Section", [
            "The JIT compiler uses type annotations to specialize instruction "
            "sequences. Type annotations record the expected NaN-box tag for "
            "each register at each instruction, allowing the JIT to emit "
            "unboxed arithmetic for registers that are always integers or "
            "always floats.",
            ("code",
             "// Type annotation record\n"
             "TypeAnnotation {\n"
             "    instr_offset: u16,\n"
             "    reg:          u8,\n"
             "    tag_mask:     u8,   // bitmask of possible tags (3 bits used)\n"
             "}\n\n"
             "// Example: register %r3 is always i64 at instruction 0x0042\n"
             "TypeAnnotation { instr_offset: 0x0042, reg: 3, tag_mask: 0b010 }"),
            "The type annotation section is generated by the AOT compiler's type "
            "inference pass and embedded in the LBC file. When the JIT encounters "
            "a register with a known single tag, it specializes the instruction: "
            "an <code>ADD</code> on two registers annotated as <code>i64</code> "
            "becomes a machine <code>ADD</code> without NaN-boxing overhead.",
        ]),
        ("3. Debug Information Schema", [
            "Debug information is stored in a dedicated LBC section that maps "
            "instruction offsets to source locations, variable names, and type "
            "information. The schema follows the DWARF5 line number table format "
            "for source mapping, with Lateralus-specific extensions for type "
            "information.",
            ("code",
             "// Debug section layout\n"
             "DebugSection {\n"
             "    source_file_table: [StringRef],  // paths to source files\n"
             "    line_number_table: LineTable,     // DWARF5 format\n"
             "    variable_table:    [VarRecord],   // name, scope, type\n"
             "    type_table:        [TypeRecord],  // Lateralus type descriptors\n"
             "}\n\n"
             "VarRecord {\n"
             "    name:       StringRef,\n"
             "    reg:        u8,      // which register holds this variable\n"
             "    scope_begin: u16,    // instruction offset where var enters scope\n"
             "    scope_end:  u16,     // instruction offset where var leaves scope\n"
             "    type_id:    u16,     // index into type_table\n"
             "}"),
            "Debuggers (including the Lateralus VS Code extension) read the "
            "debug section to provide hover-type information, watch expressions, "
            "and breakpoint setting at the source level.",
        ]),
        ("4. Pipeline Stage Metadata", [
            "Pipeline expressions in LBC carry stage metadata: for each "
            "<code>PIPE_CALL</code> instruction, a metadata record lists the "
            "operator variant, the stage index within the pipeline, and a "
            "reference to the pipeline's type annotation.",
            ("code",
             "PipelineMetadata {\n"
             "    pipeline_id:  u16,  // identifies which pipeline this stage belongs to\n"
             "    stage_index:  u8,\n"
             "    variant:      u8,   // 0=total, 1=error, 2=async, 3=fanout\n"
             "    fusable:      bool,\n"
             "    pure:         bool,\n"
             "}"),
            "The pipeline metadata enables the profiler to report per-stage latency "
            "and throughput, making it possible to identify bottleneck stages in a "
            "production pipeline.",
        ]),
        ("5. Hot-Swap Patch Format", [
            "The hot-swap format allows updating a single function in a running "
            "Lateralus process without stopping execution. A patch consists of "
            "the new function's LBC record and a patch header:",
            ("code",
             "// Hot-swap patch header\n"
             "magic:      u32   = 0x50415443  ('PATC')\n"
             "version:    u16   = 1\n"
             "target_fn:  u32   // index of function to replace\n"
             "old_crc:    u32   // CRC32 of the current function (safety check)\n"
             "new_record: FunctionRecord  // replacement function\n"
             "new_hints:  HintSection\n"
             "new_debug:  DebugSection"),
            "The runtime applies the patch by: (1) pausing threads that are "
            "currently executing the target function (they run to the next "
            "safepoint), (2) verifying the old_crc matches the current function, "
            "(3) replacing the function record and invalidating the JIT cache "
            "entry, (4) resuming paused threads which will re-enter the new "
            "function on next dispatch.",
        ]),
        ("6. Verifier", [
            "LBC files are verified before execution. The verifier checks:",
            ("list", [
                "Magic bytes and version compatibility.",
                "All instruction register references are within bounds "
                "(<code>reg &lt; n_regs</code>).",
                "All jump targets are valid instruction offsets.",
                "The constant table index in <code>LOAD_CONST</code> instructions "
                "is within bounds.",
                "The function call target in <code>CALL</code> and "
                "<code>TAIL_CALL</code> instructions exists in the file.",
                "The pipeline metadata references valid pipeline IDs.",
            ]),
            "Verification is O(N) in the number of instructions and runs in "
            "approximately 1 ms per 100,000 instructions. The verifier is always "
            "run on externally-loaded LBC files; files produced by the trusted "
            "compiler can optionally skip verification via a flag.",
        ]),
        ("7. Encoding the |?> Short-Circuit", [
            "The <code>|?></code> operator compiles to a sequence: a "
            "<code>PIPE_CALL</code> to invoke the stage, followed by a "
            "<code>PIPE_ERR_CHECK</code> that tests the result tag and jumps "
            "to the error exit block if the tag is <code>Err</code>:",
            ("code",
             "// Compiled |?> pipeline with three stages\n"
             "PIPE_CALL  %r1, fn:parse       // %r1 = parse(input)\n"
             "PIPE_ERR_CHECK %r1, label:err  // if Err, jump to err\n"
             "PIPE_CALL  %r2, fn:validate    // %r2 = validate(%r1.ok)\n"
             "PIPE_ERR_CHECK %r2, label:err\n"
             "PIPE_CALL  %r3, fn:serialize   // %r3 = serialize(%r2.ok)\n"
             "PIPE_ERR_CHECK %r3, label:err\n"
             "RET %r3\n"
             "err:\n"
             "    RET %current_err           // single error exit point"),
            "The JIT merges the three <code>PIPE_ERR_CHECK</code> targets into "
            "a single branch: all three jump to the same error block, so the "
            "branch predictor learns the single prediction for the hot path.",
        ]),
        ("8. Versioning and Stability", [
            "The LBC format version is a monotonically increasing integer in the "
            "file header. The Lateralus runtime supports reading LBC files of "
            "any version &lt;= its own version. It refuses to run files of a "
            "higher version.",
            "Backward-incompatible changes to the format increment the major "
            "version field. The current format (described in this paper and the "
            "introductory LBC paper) is version 1. Version 2 will add the "
            "compressed instruction form and structured exception table; the "
            "magic bytes will remain the same and the version field will change "
            "from 1 to 2.",
            "LBC files produced by the Lateralus 1.x compiler are guaranteed "
            "to be readable by the Lateralus 2.x runtime.",
        ]),
    ],
)

print(f"wrote {OUT}")
