"""
lateralus_lang/errors/handler.py  ─  LATERALUS Proprietary Error Handler
═══════════════════════════════════════════════════════════════════════════
The LTL error system extends the existing Lateralus error_engine with
language-level constructs:

  LTLError           — base for all language errors
  ├── LexError       — tokenisation failure
  ├── ParseError     — syntax failure
  ├── SemanticError  — type / scope failure
  ├── CompileError   — code-generation failure
  ├── VMError        — runtime VM failure
  ├── AssemblerError — .ltasm assembly failure
  └── LTLRuntimeError— user-thrown error from .ltl code

ErrorContext
    Carries the full diagnostic context:
      · source snippet + caret pointing at the column
      · error DNA fingerprint (for deduplication/archaeology)
      · severity: FATAL | ERROR | WARN | INFO | HINT
      · suggested fix  (autogenerated where possible)
      · recovery action  (for try/recover analysis)

ErrorReporter
    Collects ErrorContext objects, renders colourised console output,
    serialises to JSON for the error_engine bridge, and emits structured
    log messages.
═══════════════════════════════════════════════════════════════════════════
"""
from __future__ import annotations

import hashlib
import json
import sys
import textwrap
import traceback
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, List, Optional


# ─────────────────────────────────────────────────────────────────────────────
# Severity
# ─────────────────────────────────────────────────────────────────────────────

class Severity(Enum):
    FATAL   = 0
    ERROR   = 1
    WARNING = 2
    INFO    = 3
    HINT    = 4

    @property
    def ansi(self) -> str:
        return {
            Severity.FATAL:   "\033[1;31m",
            Severity.ERROR:   "\033[31m",
            Severity.WARNING: "\033[33m",
            Severity.INFO:    "\033[34m",
            Severity.HINT:    "\033[36m",
        }[self]


# ─────────────────────────────────────────────────────────────────────────────
# Base error types
# ─────────────────────────────────────────────────────────────────────────────

class LTLError(Exception):
    """Base class for all Lateralus Language errors."""

    def __init__(self, message: str, file: str = "<unknown>",
                 line: int = 0, col: int = 0,
                 source_line: str = "", suggestion: str = ""):
        super().__init__(message)
        self.ltl_message  = message
        self.file         = file
        self.line         = line
        self.col          = col
        self.source_line  = source_line
        self.suggestion   = suggestion

    def to_context(self, severity: Severity = Severity.ERROR) -> "ErrorContext":
        return ErrorContext(
            severity    = severity,
            code        = type(self).__name__,
            message     = self.ltl_message,
            file        = self.file,
            line        = self.line,
            col         = self.col,
            source_line = self.source_line,
            suggestion  = self.suggestion,
        )


class LTLLexError(LTLError):
    pass

class LTLParseError(LTLError):
    pass

class LTLSemanticError(LTLError):
    pass

class LTLCompileError(LTLError):
    pass

class LTLVMError(LTLError):
    pass

class LTLAssemblerError(LTLError):
    pass

class LTLRuntimeError(LTLError):
    """User-thrown error from .ltl code (THROW / recover)."""
    def __init__(self, payload: Any, file: str = "<ltl>",
                 line: int = 0, col: int = 0):
        super().__init__(str(payload), file=file, line=line, col=col)
        self.payload = payload


# ─────────────────────────────────────────────────────────────────────────────
# ErrorContext — full diagnostic record
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class StackFrame:
    """A single frame in a LATERALUS call stack."""
    function: str = "<module>"
    file:     str = "<unknown>"
    line:     int = 0
    col:      int = 0
    source:   str = ""

    def render(self, colour: bool = False) -> str:
        loc = f"{self.file}:{self.line}:{self.col}"
        fn  = f"in {self.function}" if self.function != "<module>" else "at module level"
        return f"    at {fn} ({loc})"


@dataclass
class ErrorContext:
    severity:    Severity
    code:        str              # error class name
    message:     str
    file:        str              = "<unknown>"
    line:        int              = 0
    col:         int              = 0
    source_line: str              = ""
    suggestion:  str              = ""
    notes:       List[str]        = field(default_factory=list)
    chain:       List["ErrorContext"] = field(default_factory=list)  # caused-by chain
    stack:       List[StackFrame] = field(default_factory=list)      # call stack
    context_window: List[tuple]   = field(default_factory=list)      # (line_no, text, is_error_line)
    dna:         str              = field(default="", init=False)

    def __post_init__(self):
        self.dna = self._compute_dna()

    def _compute_dna(self) -> str:
        """Structural fingerprint for deduplication (inspired by error_engine)."""
        raw = f"{self.code}:{self.file}:{self.line}:{self.message[:64]}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16]

    def location_str(self) -> str:
        return f"{self.file}:{self.line}:{self.col}"

    def render_caret(self) -> str:
        """Return source snippet with caret '^' pointing at the error column."""
        if not self.source_line:
            return ""
        col = max(0, self.col - 1)
        return f"  {self.source_line}\n  {' ' * col}^"

    def build_context_window(self, source_lines: List[str], radius: int = 3) -> None:
        """Populate context_window with surrounding source lines."""
        if not source_lines or self.line < 1:
            return
        start = max(0, self.line - 1 - radius)
        end   = min(len(source_lines), self.line + radius)
        self.context_window = [
            (i + 1, source_lines[i], (i + 1 == self.line))
            for i in range(start, end)
        ]

    def render_context_window(self, colour: bool = False) -> str:
        """Render multi-line source context with line numbers and error highlight."""
        if not self.context_window:
            return ""
        red   = "\033[31m"   if colour else ""
        dim   = "\033[2m"    if colour else ""
        reset = "\033[0m"    if colour else ""
        bold  = "\033[1m"    if colour else ""
        lines = []
        gutter = len(str(max(ln for ln, _, _ in self.context_window)))
        for ln, text, is_err in self.context_window:
            marker = ">" if is_err else " "
            num    = str(ln).rjust(gutter)
            if is_err:
                lines.append(f"  {red}{bold}{marker} {num} | {text.rstrip()}{reset}")
                col = max(0, self.col - 1)
                lines.append(f"  {red}  {' ' * gutter} | {' ' * col}^{reset}")
            else:
                lines.append(f"  {dim} {num} | {text.rstrip()}{reset}")
        return "\n".join(lines)

    def to_dict(self) -> Dict:
        d = {
            "severity":    self.severity.name,
            "code":        self.code,
            "message":     self.message,
            "file":        self.file,
            "line":        self.line,
            "col":         self.col,
            "dna":         self.dna,
            "suggestion":  self.suggestion,
            "notes":       self.notes,
        }
        if self.stack:
            d["stack"] = [{"function": f.function, "file": f.file,
                           "line": f.line} for f in self.stack]
        if self.chain:
            d["caused_by"] = [c.to_dict() for c in self.chain]
        return d


# ─────────────────────────────────────────────────────────────────────────────
# Suggestion engine  (basic auto-fix hints)
# ─────────────────────────────────────────────────────────────────────────────

_COMMON_TYPOS: Dict[str, str] = {
    "funciton":  "fn",
    "function":  "fn",
    "def":       "fn",
    "var":       "let",
    "import":    "import",
    "requires":  "import",
    "class":     "struct",
    "int":       "int",
    "printf":    "io.print",
    "print":     "io.print",
    "println":   "io.println",
    "throw":     "throw",
    "Exception": "LTLRuntimeError",
    "except":    "recover",
    "catch":     "recover",
    "finally":   "ensure",
    "elif":      "elif",
    "elseif":    "elif",
    "else if":   "elif",
}


def suggest_fix(message: str, token: str = "") -> str:
    """Generate a human-readable fix suggestion."""
    low = message.lower()
    if "undefined" in low and token:
        close = _closest_keyword(token)
        if close:
            return f"Did you mean '{close}'?"
    if "unterminated" in low:
        return "Check for a missing closing '\"', ')', ']', or '}'."
    if "unexpected" in low and "eof" in low:
        return "The file ended unexpectedly — check for unclosed blocks."
    if "expected '}'" in low:
        return "Add a closing '}' to end the block."
    if "division by zero" in low:
        return "Add a zero-check before dividing."
    if "stack underflow" in low:
        return "Ensure every CALL has a matching RET in your .ltasm code."
    if "type mismatch" in low or "type error" in low:
        return "Check that both operands have compatible types. Use 'as' for explicit casts."
    if "not callable" in low:
        return "You're trying to call something that isn't a function. Check the variable name."
    if "already defined" in low or "redefinition" in low:
        return "This name is already in scope. Use a different name or shadow with 'let'."
    if "return outside" in low:
        return "A 'return' statement can only appear inside a function body."
    if "index out of" in low or "out of range" in low:
        return "The index exceeds the collection size. Add a bounds check."
    if "import" in low and ("not found" in low or "no module" in low):
        return "Check the module path. Available stdlib: math, strings, collections, io, time, random."
    if "nil" in low and "access" in low:
        return "Use the ?-propagation operator or guard clause to handle nil values."
    return ""


def _closest_keyword(word: str) -> str:
    from difflib import get_close_matches
    candidates = list(_COMMON_TYPOS.keys()) + list(_COMMON_TYPOS.values())
    matches = get_close_matches(word, candidates, n=1, cutoff=0.7)
    return _COMMON_TYPOS.get(matches[0], matches[0]) if matches else ""


# ─────────────────────────────────────────────────────────────────────────────
# ErrorReporter
# ─────────────────────────────────────────────────────────────────────────────

_RESET = "\033[0m"
_BOLD  = "\033[1m"


class ErrorReporter:
    """
    Collects ErrorContext objects, deduplicates by DNA, renders them, and
    optionally forwards to the Lateralus error_engine bridge.
    """

    def __init__(self, source_lines: Optional[List[str]] = None,
                 use_colour: bool = True):
        self._contexts: List[ErrorContext] = []
        self._seen_dna: set = set()
        self._source_lines = source_lines or []
        self._colour       = use_colour and sys.stderr.isatty()
        self._fatal_seen   = False

    # ── add ───────────────────────────────────────────────────────────────────

    def add(self, ctx: ErrorContext) -> None:
        if ctx.dna in self._seen_dna:
            return   # deduplicate
        self._seen_dna.add(ctx.dna)
        # enrich with source line if not already present
        if not ctx.source_line and 0 < ctx.line <= len(self._source_lines):
            ctx.source_line = self._source_lines[ctx.line - 1]
        # build multi-line context window
        if self._source_lines and not ctx.context_window:
            ctx.build_context_window(self._source_lines, radius=3)
        # auto-suggest
        if not ctx.suggestion:
            ctx.suggestion = suggest_fix(ctx.message)
        self._contexts.append(ctx)
        if ctx.severity == Severity.FATAL:
            self._fatal_seen = True

    def add_exception(self, exc: Exception, severity: Severity = Severity.ERROR) -> None:
        """Wrap any Python exception as an ErrorContext."""
        if isinstance(exc, LTLError):
            self.add(exc.to_context(severity))
        else:
            ctx = ErrorContext(
                severity    = severity,
                code        = type(exc).__name__,
                message     = str(exc),
                notes       = traceback.format_exception(type(exc), exc, exc.__traceback__),
            )
            self.add(ctx)

    # ── query ─────────────────────────────────────────────────────────────────

    @property
    def has_errors(self) -> bool:
        return any(c.severity in (Severity.FATAL, Severity.ERROR)
                   for c in self._contexts)

    @property
    def has_fatal(self) -> bool:
        return self._fatal_seen

    def error_count(self) -> int:
        return sum(1 for c in self._contexts
                   if c.severity in (Severity.FATAL, Severity.ERROR))

    def warning_count(self) -> int:
        return sum(1 for c in self._contexts
                   if c.severity == Severity.WARNING)

    def all(self) -> List[ErrorContext]:
        return list(self._contexts)

    # ── render ────────────────────────────────────────────────────────────────

    def render(self, stream=None) -> None:
        stream = stream or sys.stderr
        for ctx in self._contexts:
            stream.write(self._format(ctx))
        if self._contexts:
            stream.write(
                f"\n{self._b(str(self.error_count()))} error(s), "
                f"{self._b(str(self.warning_count()))} warning(s)\n\n"
            )

    def _format(self, ctx: ErrorContext) -> str:
        sev = ctx.severity
        colour = sev.ansi if self._colour else ""
        reset  = _RESET   if self._colour else ""
        bold   = _BOLD    if self._colour else ""
        dim    = "\033[2m" if self._colour else ""
        cyan   = "\033[36m" if self._colour else ""

        lines = [f"\n{colour}{bold}[{sev.name}]{reset} "
                 f"{bold}{ctx.code}{reset}: {ctx.message}"]
        lines.append(f"  {dim}-->{reset} {ctx.location_str()}  {dim}(dna:{ctx.dna}){reset}")

        # Multi-line context window (if available), otherwise single caret
        ctx_win = ctx.render_context_window(colour=self._colour)
        if ctx_win:
            lines.append(ctx_win)
        else:
            caret = ctx.render_caret()
            if caret:
                lines.append(caret)

        if ctx.suggestion:
            lines.append(f"  {cyan}help:{reset} {ctx.suggestion}")
        for note in ctx.notes:
            lines.append(f"  {dim}note:{reset} {note.rstrip()}")

        # Stack trace (most recent call last)
        if ctx.stack:
            lines.append(f"  {dim}stack trace (most recent call last):{reset}")
            for frame in reversed(ctx.stack):
                lines.append(f"  {dim}{frame.render(self._colour)}{reset}")

        # Caused-by chain (recursive)
        for i, cause in enumerate(ctx.chain):
            indent = "  " * (i + 1)
            lines.append(f"  {dim}caused by:{reset} {cause.code}: {cause.message}")
            if cause.file != "<unknown>":
                lines.append(f"  {dim}  --> {cause.location_str()}{reset}")

        lines.append("")
        return "\n".join(lines)

    def _b(self, s: str) -> str:
        return f"{_BOLD}{s}{_RESET}" if self._colour else s

    # ── helpers ────────────────────────────────────────────────────────────────

    def chain_error(self, outer: ErrorContext, inner: ErrorContext) -> None:
        """Link inner error as the cause of outer error."""
        outer.chain.append(inner)
        self.add(outer)

    def push_stack_frame(self, ctx: ErrorContext, function: str = "<module>",
                         file: str = "<unknown>", line: int = 0, col: int = 0,
                         source: str = "") -> None:
        """Add a stack frame to the error context."""
        ctx.stack.append(StackFrame(function=function, file=file,
                                    line=line, col=col, source=source))

    def summary_line(self) -> str:
        """One-line summary for CI/script output."""
        e = self.error_count()
        w = self.warning_count()
        if e == 0 and w == 0:
            return "No errors or warnings."
        parts = []
        if e: parts.append(f"{e} error{'s' if e != 1 else ''}")
        if w: parts.append(f"{w} warning{'s' if w != 1 else ''}")
        return f"Found {', '.join(parts)}."

    # ── serialise ─────────────────────────────────────────────────────────────

    def to_json(self) -> str:
        return json.dumps([c.to_dict() for c in self._contexts], indent=2)

    def to_list(self) -> List[Dict]:
        return [c.to_dict() for c in self._contexts]
