/* AUTOGENERATED by tools/gen_grug_corpus.py — do not edit. */
/* generated: 2026-04-22 21:44:37 UTC */
#ifndef LATERALUS_GRUG_CORPUS_H
#define LATERALUS_GRUG_CORPUS_H

static const char *const GRUG_WISDOM[] = {
    "grug say: complexity very very bad. simple good.",
    "grug say: factory factory factory make grug head hurt.",
    "grug say: name variable what it be. 'data' mean nothing.",
    "grug say: if code hard to delete, code already own you.",
    "grug say: type system friend, not enemy. type catch bug.",
    "grug brain small, so grug keep function small too.",
    "grug say: senior dev is one who know where bodies buried.",
    "grug say: meeting is where productivity go to die.",
    "grug say: ship small, ship often, fix in prod, grug not scared.",
    "grug say: premature optimization root of all bug. measure first.",
    "grug say: DRY is lie. same shape not same meaning.",
    "grug say: if test hard to write, code shape wrong.",
    "grug say: comment say WHY. code already say WHAT.",
    "grug say: log loud when bad, silent when good.",
    "grug say: good name save more time than clever algorithm.",
    "grug say: grug not fear delete code. grug fear ADD code.",
    "grug say: big PR is big mistake. small diff save friendship.",
    "grug say: yak shaving is real work, just tell manager it 'infra'.",
    "grug say: dependency is stranger living in grug house forever.",
    "grug say: if build slow, grug get slower too.",
    "grug say: mock only edge of world. mock inside is lie to self.",
    "grug say: cache is where grug bury past mistakes.",
    "grug say: async is just sync with more ways to lose.",
    "grug say: null is billion-dollar mistake. maybe is cheaper.",
    "grug say: microservice is distributed monolith wearing funny hat.",
    "grug say: k8s yaml longer than actual program. grug cry.",
    "grug say: if you scared to touch code, code is now museum.",
    "grug say: tests are letters from past grug to future grug.",
    "grug say: log before you leap, trace before you weep.",
    "grug say: first rule of debug club: read the error message.",
    "grug say: second rule of debug club: ACTUALLY read error message.",
    "grug say: grep beats grand unified theory every time.",
    "grug say: regex is just line noise that passed code review.",
    "grug say: clever code is job security spelled slowly.",
    "grug say: if grug need comment to explain WHAT, code lie about WHY.",
    "grug say: state machine small, bug small. state machine big, bug eternal.",
    "grug say: ORM is abstraction for people who scared of SELECT.",
    "grug say: if two service share table, one service pretending.",
    "grug say: scaling horizontal easy. scaling culture hard.",
    "grug say: observability is just logging with a marketing budget.",
};
static const int GRUG_WISDOM_N = (int)(sizeof(GRUG_WISDOM)/sizeof(GRUG_WISDOM[0]));

static const char *const GRUG_JOKES[] = {
    "why function cross road? because callback on other side.",
    "grug have 99 problem but null pointer not one. grug also have null.",
    "how many grug to change lightbulb? none. grug afraid of dark.",
    "grug try recursion to understand recursion. grug still trying.",
    "wife say get bread, if egg get 12. he come home with 12 bread.",
    "why programmer no like nature? too many bugs outside too.",
    "grug knock knock. who there. race condition. race condition who? knock knock.",
    "grug algorithm O(1). grug couch also O(1). coincidence? no.",
    "how grug center div? grug still trying. it been 9 year.",
    "why unix guru quiet? because cat got their tongue. and their pipe.",
    "sql query walk into bar, see two table. say 'mind if i JOIN you?'.",
    "programmer dream in vim. programmer nightmare is exiting vim.",
    "why grug love pointers? because they POINT out grug mistake.",
    "grug wife say: talk dirty to me. grug whisper: 'unindexed query'.",
    "boss ask grug estimate. grug say 2 week. always 2 week. forever 2 week.",
    "grug write bug-free code once. compiler was broken.",
    "why grug language dynamic? because grug too lazy for type. also too small brain.",
    "regex walk in bar, bar explode, three more bar appear.",
    "manager say move fast break thing. grug move fast break manager.",
    "grug stackoverflow answer marked duplicate of grug's own question.",
};
static const int GRUG_JOKES_N = (int)(sizeof(GRUG_JOKES)/sizeof(GRUG_JOKES[0]));

static const char *const GRUG_SMOKE[] = {
    "grug puff... semicolons are just fences for thoughts.",
    "grug puff... garbage collector is just letting go man.",
    "grug puff... monad is just burrito of sadness.",
    "grug puff... every for-loop is a tiny universe bro.",
    "grug puff... types are vibes and vibes are types.",
    "grug puff... the real bug was friends we made along the way.",
    "grug puff... if tree commit in forest and no CI run, did build pass?",
    "grug puff... pointer point to feeling, feeling point to pointer.",
    "grug puff... the closure is just a hug around a variable man.",
    "grug puff... every unit test is a letter to your future self.",
    "grug puff... the pipe symbol is just tao flowing through shell.",
    "grug puff... null is not empty, null is infinite potential.",
    "grug puff... recursion is just falling with style.",
    "grug puff... the real distributed system was inside us all along.",
    "grug puff... race condition? more like dance condition.",
    "grug puff... kubernetes is just cgroups dressed for prom.",
    "grug puff... /dev/null is where unspoken truths go to rest.",
};
static const int GRUG_SMOKE_N = (int)(sizeof(GRUG_SMOKE)/sizeof(GRUG_SMOKE[0]));

typedef struct {
    const char *const *keywords;  /* NULL-terminated */
    const char *response;
} GrugRule;

static const char *const GRUG_RULE_KW_0[] = {"docker", "container", "k8s", "kube", "helm", (const char*)0 };
static const char *const GRUG_RULE_KW_1[] = {"database", "postgres", "mysql", "sqlite", "db", (const char*)0 };
static const char *const GRUG_RULE_KW_2[] = {"git", "merge", "rebase", "conflict", (const char*)0 };
static const char *const GRUG_RULE_KW_3[] = {"security", "auth", "password", "secret", "token", (const char*)0 };
static const char *const GRUG_RULE_KW_4[] = {"api", "rest", "graphql", "grpc", (const char*)0 };
static const char *const GRUG_RULE_KW_5[] = {"frontend", "react", "vue", "angular", "css", (const char*)0 };
static const char *const GRUG_RULE_KW_6[] = {"backend", "server", "microservice", "mono", (const char*)0 };
static const char *const GRUG_RULE_KW_7[] = {"machine learning", "ml", "neural", "tensor", "model", (const char*)0 };
static const char *const GRUG_RULE_KW_8[] = {"cloud", "aws", "azure", "gcp", "lambda", (const char*)0 };
static const char *const GRUG_RULE_KW_9[] = {"linux", "unix", "shell", "bash", "zsh", (const char*)0 };
static const char *const GRUG_RULE_KW_10[] = {"vim", "emacs", "editor", "ide", (const char*)0 };
static const char *const GRUG_RULE_KW_11[] = {"blockchain", "crypto", "web3", "nft", (const char*)0 };
static const char *const GRUG_RULE_KW_12[] = {"legacy", "old code", "mainframe", (const char*)0 };
static const char *const GRUG_RULE_KW_13[] = {"spec", "design", "doc", "whiteboard", (const char*)0 };
static const char *const GRUG_RULE_KW_14[] = {"deadline", "crunch", "overtime", "burnout", (const char*)0 };
static const char *const GRUG_RULE_KW_15[] = {"code review", "pr", "pull request", "lgtm", (const char*)0 };
static const char *const GRUG_RULE_KW_16[] = {"memory leak", "heap", "stack", "segfault", (const char*)0 };
static const char *const GRUG_RULE_KW_17[] = {"concurrency", "thread", "mutex", "lock", "atomic", (const char*)0 };
static const char *const GRUG_RULE_KW_18[] = {"null pointer", "nullptr", "undefined", "nan", (const char*)0 };
static const char *const GRUG_RULE_KW_19[] = {"latency", "throughput", "bottleneck", (const char*)0 };
static const char *const GRUG_RULE_KW_20[] = {"monitoring", "metric", "alert", "pager", (const char*)0 };
static const char *const GRUG_RULE_KW_21[] = {"feature flag", "ab test", "rollout", (const char*)0 };
static const char *const GRUG_RULE_KW_22[] = {"accessibility", "a11y", "screen reader", (const char*)0 };
static const char *const GRUG_RULE_KW_23[] = {"logging", "trace", "span", "observability", (const char*)0 };
static const char *const GRUG_RULE_KW_24[] = {"interview", "whiteboard", "leetcode", (const char*)0 };
static const char *const GRUG_RULE_KW_25[] = {"money", "salary", "raise", "promo", (const char*)0 };
static const char *const GRUG_RULE_KW_26[] = {"documentation", "readme", "wiki", (const char*)0 };
static const char *const GRUG_RULE_KW_27[] = {"technical debt", "tech debt", "cleanup", (const char*)0 };
static const char *const GRUG_RULE_KW_28[] = {"startup", "scale", "growth", (const char*)0 };
static const char *const GRUG_RULE_KW_29[] = {"remote", "wfh", "office", "hybrid", (const char*)0 };

static const GrugRule GRUG_RULES[] = {
    { GRUG_RULE_KW_0, "container is cage for app. good. distributed cage less good." },
    { GRUG_RULE_KW_1, "database is source of truth. rest is cache pretending." },
    { GRUG_RULE_KW_2, "rebase is rewrite history. merge is accept history. grug merge." },
    { GRUG_RULE_KW_3, "secret in code is secret to world. env var is rental cave." },
    { GRUG_RULE_KW_4, "api is contract. grug not break contract unless version bump." },
    { GRUG_RULE_KW_5, "css is where senior dev cry quietly. grug mostly use flex." },
    { GRUG_RULE_KW_6, "monolith first. split only when pain real, not imagined." },
    { GRUG_RULE_KW_7, "model is fancy lookup table with extra steps and bigger bill." },
    { GRUG_RULE_KW_8, "cloud is someone else computer, and someone else bill." },
    { GRUG_RULE_KW_9, "shell is duct tape of gods. grug love duct tape." },
    { GRUG_RULE_KW_10, "editor war is cave war. grug pick one, grug learn one, grug ship." },
    { GRUG_RULE_KW_11, "grug not trust chain that need spokesperson to work." },
    { GRUG_RULE_KW_12, "legacy mean code that pay bills. respect legacy." },
    { GRUG_RULE_KW_13, "grug draw boxes before grug draw code. past grug thank present grug." },
    { GRUG_RULE_KW_14, "tired grug write bug. bug cost more than deadline save." },
    { GRUG_RULE_KW_15, "review is gift. grug review kind but honest." },
    { GRUG_RULE_KW_16, "memory leak is slow monster. free what you malloc. own what you borrow." },
    { GRUG_RULE_KW_17, "shared mutable state is dragon. grug not wake dragon." },
    { GRUG_RULE_KW_18, "null is grug's oldest enemy. option type is shield." },
    { GRUG_RULE_KW_19, "measure, don't guess. profile before you promise." },
    { GRUG_RULE_KW_20, "alert on symptom, not cause. grug sleep better." },
    { GRUG_RULE_KW_21, "flag is dimmer switch on new code. flip slow, watch graph." },
    { GRUG_RULE_KW_22, "accessibility is good code, not charity. grug use keyboard too." },
    { GRUG_RULE_KW_23, "log context not just facts. future grug need breadcrumb." },
    { GRUG_RULE_KW_24, "interview test nerves, not code. breathe. talk out loud." },
    { GRUG_RULE_KW_25, "code pay rent. negotiate like grug hunt: calm, prepared, patient." },
    { GRUG_RULE_KW_26, "readme first, fancy site never. 10 line README beats 100 page wiki." },
    { GRUG_RULE_KW_27, "tech debt is fine, just pay interest on time." },
    { GRUG_RULE_KW_28, "premature scaling is how startup die. make thing people want first." },
    { GRUG_RULE_KW_29, "grug work best where grug can think. culture > location." },
};
static const int GRUG_RULES_N = (int)(sizeof(GRUG_RULES)/sizeof(GRUG_RULES[0]));

#define GRUG_TRAINING_WISDOM_N  40
#define GRUG_TRAINING_JOKES_N   20
#define GRUG_TRAINING_SMOKE_N   17
#define GRUG_TRAINING_RULES_N   30
#define GRUG_TRAINING_TOTAL     227

#endif /* LATERALUS_GRUG_CORPUS_H */
