"""
lateralus_lang/ir.py  ─  LATERALUS Intermediate Representation
═══════════════════════════════════════════════════════════════════════════
Three-address code (TAC) IR used between the AST and code generators.

IR Instructions
───────────────
  Each IRInstr holds:
    op      — IROp enum
    dest    — destination temporary or label (str)
    src1    — first operand (str, int, float, bool, None)
    src2    — second operand

  Function is the unit of compilation.
  A Function contains a list of BasicBlock.
  A BasicBlock contains a list of IRInstr.

Temporary naming
────────────────
  Temporaries: %0, %1, %2, …  (generated by IRBuilder)
  Labels:      L0, L1, L2, …
  Globals:     @name
  Parameters:  $name

Semantic analysis
─────────────────
  SemanticAnalyzer walks the AST, builds the symbol table (scope chain),
  infers types, and emits IR.  Type errors are collected (non-fatal) and
  surfaced through the error bridge.
═══════════════════════════════════════════════════════════════════════════
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, List, Optional, Tuple

from .ast_nodes import (
    AssignStmt, ASTVisitor, AwaitExpr, BinOp, BlockStmt, BreakStmt,
    CallExpr, CastExpr, ContinueStmt, EnumDecl, ExprStmt, FieldExpr, FnDecl,
    ForeignBlock, ForeignParam,
    ForStmt, Ident, IfStmt, ImplBlock, ImportStmt, IndexExpr, InterfaceDecl,
    InterpolatedStr, LambdaExpr, LetDecl, ListExpr, Literal, LoopStmt, MapExpr,
    MatchStmt, Node, Param, Program, RangeExpr, ReturnStmt, SelfExpr,
    SourceSpan, SpawnExpr, StructDecl, StructLiteral, TryStmt, TupleExpr,
    TypeAlias, TypeRef, UnaryOp, WhileStmt, YieldExpr,
    ThrowStmt, TryExpr, EmitStmt, ProbeExpr, MeasureBlock,
    ChainExpr, PropagateExpr, ComprehensionExpr, GuardExpr, WhereClause,
    PipelineAssign, SpreadExpr, TernaryExpr,
)


# ─────────────────────────────────────────────────────────────────────────────
# IR opcode
# ─────────────────────────────────────────────────────────────────────────────

class IROp(Enum):
    # Moves / assignment
    COPY       = auto()   # dest = src1
    LOAD_IMM   = auto()   # dest = <literal>
    LOAD_STR   = auto()   # dest = <string literal>
    LOAD_BOOL  = auto()
    LOAD_NIL   = auto()

    # Arithmetic / logic
    ADD   = auto()  # dest = src1 + src2
    SUB   = auto()
    MUL   = auto()
    DIV   = auto()
    MOD   = auto()
    POW   = auto()
    NEG   = auto()  # dest = -src1
    NOT   = auto()  # dest = !src1
    BNOT  = auto()  # dest = ~src1
    AND   = auto()
    OR    = auto()
    XOR   = auto()
    SHL   = auto()
    SHR   = auto()

    # Comparison
    EQ    = auto()
    NE    = auto()
    LT    = auto()
    LE    = auto()
    GT    = auto()
    GE    = auto()

    # Control flow
    LABEL    = auto()   # define a label (dest = label name)
    JMP      = auto()   # goto dest
    JT       = auto()   # if src1 goto dest
    JF       = auto()   # if not src1 goto dest
    CALL     = auto()   # dest = call src1(args…)   src2=arg_list
    RETURN   = auto()   # return src1
    HALT     = auto()

    # Collections
    MAKE_LIST = auto()  # dest = [src1, …]  src2=count
    MAKE_MAP  = auto()
    INDEX     = auto()  # dest = src1[src2]
    SET_IDX   = auto()  # src1[src2] = dest

    # Field access
    GET_FIELD = auto()  # dest = src1.src2
    SET_FIELD = auto()  # src1.src2 = dest

    # Error handling
    TRY_ENTER = auto()  # dest = recover_label
    TRY_LEAVE = auto()
    THROW     = auto()  # throw src1
    BIND_ERR  = auto()  # dest = caught_error (in recover block)
    ENSURE    = auto()  # dest = ensure_label

    # Type
    CAST      = auto()  # dest = cast(src1, src2_type)
    TYPEOF    = auto()
    SIZEOF    = auto()

    # Pipeline
    PIPE      = auto()  # dest = src2(src1)  (a |> f)

    # Async
    AWAIT     = auto()  # dest = await src1
    YIELD     = auto()

    # Misc
    NOP       = auto()
    COMMENT   = auto()  # dest = comment text (stripped in final codegen)

    # v1.1 – Structs / Enums
    MAKE_STRUCT  = auto()  # dest = struct_type_name, src1 = [(field, tmp), ...]
    GET_STRUCT_F = auto()  # dest = src1.field_name   (src2 = field name str)
    SET_STRUCT_F = auto()  # src1.src2 = dest
    DEFINE_STRUCT= auto()  # register struct type  (src1 = type_name, src2 = fields)
    MAKE_ENUM    = auto()  # dest = EnumVariant(src1_name, src2_data)
    DEFINE_ENUM  = auto()  # register enum type
    TYPE_ALIAS   = auto()  # record type alias   (src1 = alias, src2 = target)
    SELF_REF     = auto()  # dest = self reference in method context
    YIELD_VAL    = auto()  # yield src1
    SPAWN_TASK   = auto()  # dest = spawn(src1)
    INTERP_STR   = auto()  # dest = interpolated string (src1 = parts list)
    FOREIGN_CALL = auto()  # dest = polyglot call (extra={'lang':…, 'source':…, 'params':…})
    COND_SELECT  = auto()  # dest = src1 ? extra.true : extra.false (ternary)


# ─────────────────────────────────────────────────────────────────────────────
# IR structures
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class IRInstr:
    op:    IROp
    dest:  Optional[str]  = None
    src1:  Any            = None
    src2:  Any            = None
    span:  Optional[SourceSpan] = None
    extra: Any            = None   # opcode-specific payload (e.g. FOREIGN_CALL metadata)

    def __str__(self) -> str:
        parts = [self.op.name]
        if self.dest  is not None: parts.append(f"{self.dest}")
        if self.src1  is not None: parts.append(f"{self.src1!r}")
        if self.src2  is not None: parts.append(f"{self.src2!r}")
        if self.extra is not None: parts.append(f"extra={self.extra!r}")
        return "  " + "  ".join(parts)


@dataclass
class BasicBlock:
    label:   str
    instrs:  List[IRInstr] = field(default_factory=list)
    preds:   List[str]     = field(default_factory=list)
    succs:   List[str]     = field(default_factory=list)


@dataclass
class IRFunction:
    name:     str
    params:   List[str]                       = field(default_factory=list)
    blocks:   List[BasicBlock]                = field(default_factory=list)
    is_async: bool                            = False
    ret_type: Optional[str]                   = None
    span:     Optional[SourceSpan]            = None

    def entry_block(self) -> BasicBlock:
        return self.blocks[0] if self.blocks else self._new_block("entry")

    def _new_block(self, label: str) -> BasicBlock:
        bb = BasicBlock(label=label)
        self.blocks.append(bb)
        return bb


@dataclass
class IRModule:
    name:      str
    functions: List[IRFunction]   = field(default_factory=list)
    globals_:  List[IRInstr]      = field(default_factory=list)   # top-level


# ─────────────────────────────────────────────────────────────────────────────
# Symbol table
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Symbol:
    name:      str
    kind:      str          # "var" | "fn" | "param" | "const"
    type_:     Optional[str]
    mutable:   bool = True
    temp_name: Optional[str] = None   # IR temporary bound to this symbol


class Scope:
    def __init__(self, parent: Optional["Scope"] = None, name: str = "<scope>"):
        self.parent   = parent
        self.name     = name
        self._symbols: Dict[str, Symbol] = {}

    def define(self, sym: Symbol) -> None:
        self._symbols[sym.name] = sym

    def resolve(self, name: str) -> Optional[Symbol]:
        if name in self._symbols:
            return self._symbols[name]
        if self.parent:
            return self.parent.resolve(name)
        return None

    def child(self, name: str = "<child>") -> "Scope":
        return Scope(parent=self, name=name)


# ─────────────────────────────────────────────────────────────────────────────
# Semantic errors
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class SemanticError:
    message: str
    span:    Optional[SourceSpan]
    level:   str = "error"   # "error" | "warning" | "info"

    def __str__(self) -> str:
        loc = str(self.span) if self.span else "?"
        return f"[{self.level.upper()}] {loc}: {self.message}"


# ─────────────────────────────────────────────────────────────────────────────
# IR Builder  (helper to emit IR instructions)
# ─────────────────────────────────────────────────────────────────────────────

class IRBuilder:
    def __init__(self):
        self._tmp_counter   = 0
        self._label_counter = 0

    def new_tmp(self) -> str:
        n = self._tmp_counter
        self._tmp_counter += 1
        return f"%{n}"

    def new_label(self, hint: str = "L") -> str:
        n = self._label_counter
        self._label_counter += 1
        return f"{hint}{n}"

    @staticmethod
    def emit(bb: BasicBlock, op: IROp, dest=None, src1=None, src2=None,
             span=None, extra=None) -> IRInstr:
        instr = IRInstr(op=op, dest=dest, src1=src1, src2=src2, span=span,
                        extra=extra)
        bb.instrs.append(instr)
        return instr


# ─────────────────────────────────────────────────────────────────────────────
# Semantic Analyzer + IR Generator
# ─────────────────────────────────────────────────────────────────────────────

class SemanticAnalyzer(ASTVisitor):
    """
    Walks the AST.
      1. Builds scope chain (symbol table)
      2. Infers basic types
      3. Reports semantic errors
      4. Emits three-address IR
    """

    def __init__(self, filename: str = "<unknown>"):
        self._file    = filename
        self.errors:  List[SemanticError] = []
        self._builder = IRBuilder()
        self._scope   = Scope(name="global")
        self._current_fn:  Optional[IRFunction]   = None
        self._current_bb:  Optional[BasicBlock]   = None
        self._module:      Optional[IRModule]      = None
        # loop context stacks for break/continue
        self._break_labels:    List[str] = []
        self._continue_labels: List[str] = []

    # ── public entry ──────────────────────────────────────────────────────────

    # ── builtin names always available ───────────────────────────────────────
    _BUILTINS = [
        "println", "print", "len", "str", "int", "float", "bool",
        "range", "push", "pop", "keys", "values", "items",
        "type", "error", "assert",
        "slice", "slice_list", "list_copy", "list_set", "list_contains",
        "str_upper", "str_lower",
        "sleep_ms", "next",
        "io", "math", "os", "sys",
    ]

    def analyze(self, program: Program) -> IRModule:
        mod_name = program.module or "main"
        self._module = IRModule(name=mod_name)
        # Pre-populate global scope with builtins
        for name in self._BUILTINS:
            self._scope.define(Symbol(name=name, kind="builtin",
                                      type_="fn", mutable=False))
        program.accept(self)
        return self._module

    # ── error helpers ─────────────────────────────────────────────────────────

    def _error(self, msg: str, span: Optional[SourceSpan] = None) -> None:
        self.errors.append(SemanticError(msg, span, level="error"))

    def _warn(self, msg: str, span: Optional[SourceSpan] = None) -> None:
        self.errors.append(SemanticError(msg, span, level="warning"))

    # ── scope helpers ─────────────────────────────────────────────────────────

    def _push_scope(self, name: str = "<block>") -> None:
        self._scope = self._scope.child(name)

    def _pop_scope(self) -> None:
        if self._scope.parent:
            self._scope = self._scope.parent

    # ── bb helpers ────────────────────────────────────────────────────────────

    def _new_bb(self, hint: str = "BB") -> BasicBlock:
        assert self._current_fn is not None
        label = self._builder.new_label(hint)
        bb = BasicBlock(label=label)
        self._current_fn.blocks.append(bb)
        return bb

    def _emit(self, op: IROp, dest=None, src1=None, src2=None,
              span=None, extra=None) -> IRInstr:
        bb = self._current_bb or self._global_bb()
        return self._builder.emit(bb, op, dest=dest, src1=src1,
                                  src2=src2, span=span, extra=extra)

    def _global_bb(self) -> BasicBlock:
        # Synthesize a global init function if needed
        if not self._module.globals_:
            pass
        instr = IRInstr(op=IROp.NOP)
        self._module.globals_.append(instr)
        return BasicBlock(label="__global__", instrs=self._module.globals_)

    # ── visitor implementations ───────────────────────────────────────────────

    def visit_Program(self, node: Program):
        for imp in node.imports:
            imp.accept(self)
        # We need an IR function context for any top-level control-flow statements.
        # Create a synthetic __toplevel__ function that wraps the module body.
        _needs_fn_ctx = (
            IfStmt, WhileStmt, ForStmt, LoopStmt,
            TryStmt, MatchStmt, AssignStmt, ExprStmt,
            LetDecl, ReturnStmt,
        )
        toplevel_stmts = [s for s in node.body if isinstance(s, _needs_fn_ctx)]
        if toplevel_stmts:
            tl_fn = IRFunction(name="__toplevel__", is_async=False,
                               span=node.span)
            self._module.functions.append(tl_fn)
            outer_fn  = self._current_fn
            outer_bb  = self._current_bb
            self._current_fn = tl_fn
            entry_bb = BasicBlock(label="entry")
            tl_fn.blocks.append(entry_bb)
            self._current_bb = entry_bb
            outer_scope = self._scope
            self._scope = Scope(parent=outer_scope, name="__toplevel__")

            for stmt in node.body:
                stmt.accept(self)

            self._current_fn  = outer_fn
            self._current_bb  = outer_bb
            self._scope       = outer_scope
        else:
            for stmt in node.body:
                stmt.accept(self)

    def visit_ImportStmt(self, node: ImportStmt):
        # Record as a symbol (resolved at runtime)
        alias = node.alias or node.path.split(".")[-1]
        self._scope.define(Symbol(name=alias, kind="import",
                                  type_="module", mutable=False))

    def visit_FnDecl(self, node: FnDecl):
        fn = IRFunction(name=node.name, is_async=node.is_async,
                        span=node.span)
        self._module.functions.append(fn)
        # Register in scope
        self._scope.define(Symbol(name=node.name, kind="fn",
                                  type_="fn", mutable=False))
        # Enter function scope
        outer_fn = self._current_fn
        outer_bb = self._current_bb
        self._current_fn = fn
        self._push_scope(node.name)

        entry_bb = BasicBlock(label="entry")
        fn.blocks.append(entry_bb)
        self._current_bb = entry_bb

        for p in node.params:
            fn.params.append(p.name)
            sym = Symbol(name=p.name, kind="param", type_=None, mutable=False,
                         temp_name=f"${p.name}")
            self._scope.define(sym)

        if node.body:
            node.body.accept(self)

        self._pop_scope()
        self._current_fn = outer_fn
        self._current_bb = outer_bb

    def visit_LetDecl(self, node: LetDecl):
        tmp = self._builder.new_tmp()
        sym = Symbol(name=node.name, kind="const" if node.is_const else "var",
                     type_=str(node.type_) if node.type_ else None,
                     mutable=node.mutable, temp_name=tmp)
        self._scope.define(sym)
        if node.value:
            val_tmp = node.value.accept(self)
            self._emit(IROp.COPY, dest=tmp, src1=val_tmp, span=node.span)
        else:
            self._emit(IROp.LOAD_NIL, dest=tmp, span=node.span)

    def visit_ReturnStmt(self, node: ReturnStmt):
        if node.value:
            val = node.value.accept(self)
            self._emit(IROp.RETURN, src1=val, span=node.span)
        else:
            self._emit(IROp.RETURN, span=node.span)

    def visit_IfStmt(self, node: IfStmt):
        cond_tmp = node.condition.accept(self)
        then_label  = self._builder.new_label("then")
        after_label = self._builder.new_label("after")
        else_label  = self._builder.new_label("else") if node.else_block else after_label

        self._emit(IROp.JF, dest=else_label, src1=cond_tmp, span=node.span)

        then_bb = self._new_bb(then_label)
        self._current_bb = then_bb
        self._emit(IROp.LABEL, dest=then_label)
        node.then_block.accept(self)
        self._emit(IROp.JMP, dest=after_label)

        if node.else_block:
            else_bb = self._new_bb(else_label)
            self._current_bb = else_bb
            self._emit(IROp.LABEL, dest=else_label)
            node.else_block.accept(self)
            self._emit(IROp.JMP, dest=after_label)

        after_bb = self._new_bb(after_label)
        self._current_bb = after_bb
        self._emit(IROp.LABEL, dest=after_label)

    def visit_WhileStmt(self, node: WhileStmt):
        cond_label  = self._builder.new_label("wcond")
        body_label  = self._builder.new_label("wbody")
        after_label = self._builder.new_label("wafter")
        self._break_labels.append(after_label)
        self._continue_labels.append(cond_label)

        self._emit(IROp.JMP, dest=cond_label)
        cond_bb = self._new_bb(cond_label)
        self._current_bb = cond_bb
        self._emit(IROp.LABEL, dest=cond_label)
        cond_tmp = node.condition.accept(self)
        self._emit(IROp.JF, dest=after_label, src1=cond_tmp)

        body_bb = self._new_bb(body_label)
        self._current_bb = body_bb
        self._emit(IROp.LABEL, dest=body_label)
        node.body.accept(self)
        self._emit(IROp.JMP, dest=cond_label)

        after_bb = self._new_bb(after_label)
        self._current_bb = after_bb
        self._emit(IROp.LABEL, dest=after_label)
        self._break_labels.pop()
        self._continue_labels.pop()

    def visit_ForStmt(self, node: ForStmt):
        iter_tmp    = node.iter.accept(self)
        idx_tmp     = self._builder.new_tmp()
        item_tmp    = self._builder.new_tmp()
        cond_label  = self._builder.new_label("fcond")
        body_label  = self._builder.new_label("fbody")
        after_label = self._builder.new_label("fafter")
        self._break_labels.append(after_label)
        self._continue_labels.append(cond_label)

        self._emit(IROp.LOAD_IMM, dest=idx_tmp, src1=0)
        self._emit(IROp.JMP, dest=cond_label)

        cond_bb = self._new_bb(cond_label)
        self._current_bb = cond_bb
        self._emit(IROp.LABEL, dest=cond_label)
        len_tmp = self._builder.new_tmp()
        self._emit(IROp.SIZEOF, dest=len_tmp, src1=iter_tmp)
        cond_tmp = self._builder.new_tmp()
        self._emit(IROp.LT, dest=cond_tmp, src1=idx_tmp, src2=len_tmp)
        self._emit(IROp.JF, dest=after_label, src1=cond_tmp)

        body_bb = self._new_bb(body_label)
        self._current_bb = body_bb
        self._emit(IROp.LABEL, dest=body_label)
        self._emit(IROp.INDEX, dest=item_tmp, src1=iter_tmp, src2=idx_tmp)
        sym = Symbol(name=node.var, kind="var", type_=None, mutable=False,
                     temp_name=item_tmp)
        self._push_scope("for")
        self._scope.define(sym)
        node.body.accept(self)
        self._pop_scope()
        self._emit(IROp.ADD, dest=idx_tmp, src1=idx_tmp, src2=1)
        self._emit(IROp.JMP, dest=cond_label)

        after_bb = self._new_bb(after_label)
        self._current_bb = after_bb
        self._emit(IROp.LABEL, dest=after_label)
        self._break_labels.pop()
        self._continue_labels.pop()

    def visit_BreakStmt(self, node):
        if self._break_labels:
            self._emit(IROp.JMP, dest=self._break_labels[-1], span=node.span)
        else:
            self._error("'break' outside loop", node.span)

    def visit_ContinueStmt(self, node):
        if self._continue_labels:
            self._emit(IROp.JMP, dest=self._continue_labels[-1], span=node.span)
        else:
            self._error("'continue' outside loop", node.span)

    def visit_TryStmt(self, node: TryStmt):
        recover_label = self._builder.new_label("recover")
        after_label   = self._builder.new_label("try_after")
        ensure_label  = self._builder.new_label("ensure") if node.ensure else None

        self._emit(IROp.TRY_ENTER, dest=recover_label, span=node.span)
        node.body.accept(self)
        self._emit(IROp.TRY_LEAVE)
        self._emit(IROp.JMP, dest=after_label)

        rec_bb = self._new_bb(recover_label)
        self._current_bb = rec_bb
        self._emit(IROp.LABEL, dest=recover_label)
        for clause in node.recoveries:
            err_tmp = self._builder.new_tmp()
            self._emit(IROp.BIND_ERR, dest=err_tmp)
            if clause.binding:
                sym = Symbol(name=clause.binding, kind="var", type_=None,
                             mutable=False, temp_name=err_tmp)
                self._push_scope("recover")
                self._scope.define(sym)
            clause.body.accept(self)
            if clause.binding:
                self._pop_scope()

        if ensure_label:
            self._emit(IROp.ENSURE, dest=ensure_label)
            ensure_bb = self._new_bb(ensure_label)
            self._current_bb = ensure_bb
            self._emit(IROp.LABEL, dest=ensure_label)
            node.ensure.accept(self)

        after_bb = self._new_bb(after_label)
        self._current_bb = after_bb
        self._emit(IROp.LABEL, dest=after_label)

    def visit_ExprStmt(self, node: ExprStmt):
        node.expr.accept(self)

    def visit_AssignStmt(self, node: AssignStmt):
        rhs_tmp = node.value.accept(self)
        if isinstance(node.target, Ident):
            sym = self._scope.resolve(node.target.name)
            if sym is None:
                self._warn(f"Undefined variable '{node.target.name}'", node.span)
                return
            if not sym.mutable and sym.kind == "const":
                self._error(f"Cannot reassign const '{node.target.name}'", node.span)
            dest = sym.temp_name or sym.name
            if node.op == "=":
                self._emit(IROp.COPY, dest=dest, src1=rhs_tmp)
            else:
                bin_op_map = {
                    "+=": IROp.ADD, "-=": IROp.SUB, "*=": IROp.MUL,
                    "/=": IROp.DIV, "%=": IROp.MOD, "**=": IROp.POW,
                }
                bin_op = bin_op_map.get(node.op, IROp.ADD)
                self._emit(bin_op, dest=dest, src1=dest, src2=rhs_tmp)

    def visit_BlockStmt(self, node: BlockStmt):
        self._push_scope()
        for stmt in node.stmts:
            if stmt is None:
                continue
            stmt.accept(self)
        self._pop_scope()

    # ── expression visitors (return tmp name) ─────────────────────────────────

    def visit_Literal(self, node: Literal) -> str:
        tmp = self._builder.new_tmp()
        op_map = {"int": IROp.LOAD_IMM, "float": IROp.LOAD_IMM,
                  "str": IROp.LOAD_STR, "bool": IROp.LOAD_BOOL,
                  "nil":  IROp.LOAD_NIL}
        self._emit(op_map.get(node.kind, IROp.LOAD_IMM),
                   dest=tmp, src1=node.value, span=node.span)
        return tmp

    def visit_Ident(self, node: Ident) -> str:
        sym = self._scope.resolve(node.name)
        if sym is None:
            # Emit a warning (not error) for undefined names — snippets and
            # partial programs often rely on external bindings resolved at runtime.
            self._warn(f"Undefined name '{node.name}'", node.span)
            tmp = self._builder.new_tmp()
            self._emit(IROp.LOAD_NIL, dest=tmp, span=node.span)
            return tmp
        return sym.temp_name or (f"${sym.name}" if sym.kind == "param" else sym.name)

    def visit_BinOp(self, node: BinOp) -> str:
        op_map = {
            "+": IROp.ADD,  "-": IROp.SUB,  "*": IROp.MUL,  "/": IROp.DIV,
            "%": IROp.MOD,  "**": IROp.POW, "&": IROp.AND,  "|": IROp.OR,
            "^": IROp.XOR,  "<<": IROp.SHL, ">>": IROp.SHR,
            "==": IROp.EQ,  "!=": IROp.NE,  "<": IROp.LT,   "<=": IROp.LE,
            ">": IROp.GT,   ">=": IROp.GE,
            "&&": IROp.AND, "||": IROp.OR,
            "|>": IROp.PIPE,
        }
        if node.op == "|>":
            left_tmp  = node.left.accept(self)
            right_tmp = node.right.accept(self)
            tmp = self._builder.new_tmp()
            self._emit(IROp.PIPE, dest=tmp, src1=left_tmp, src2=right_tmp, span=node.span)
            return tmp
        left_tmp  = node.left.accept(self)
        right_tmp = node.right.accept(self)
        tmp = self._builder.new_tmp()
        ir_op = op_map.get(node.op, IROp.ADD)
        self._emit(ir_op, dest=tmp, src1=left_tmp, src2=right_tmp, span=node.span)
        return tmp

    def visit_UnaryOp(self, node: UnaryOp) -> str:
        op_map = {"-": IROp.NEG, "!": IROp.NOT, "~": IROp.BNOT,
                  "typeof": IROp.TYPEOF, "sizeof": IROp.SIZEOF}
        operand_tmp = node.operand.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(op_map.get(node.op, IROp.NEG),
                   dest=tmp, src1=operand_tmp, span=node.span)
        return tmp

    def visit_CallExpr(self, node: CallExpr) -> str:
        callee_tmp = node.callee.accept(self)
        arg_tmps   = [a.accept(self) for a in node.args]
        tmp = self._builder.new_tmp()
        self._emit(IROp.CALL, dest=tmp, src1=callee_tmp,
                   src2=arg_tmps, span=node.span)
        return tmp

    def visit_IndexExpr(self, node: IndexExpr) -> str:
        obj_tmp = node.obj.accept(self)
        idx_tmp = node.index.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.INDEX, dest=tmp, src1=obj_tmp, src2=idx_tmp, span=node.span)
        return tmp

    def visit_FieldExpr(self, node: FieldExpr) -> str:
        obj_tmp = node.obj.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.GET_FIELD, dest=tmp, src1=obj_tmp,
                   src2=node.field, span=node.span)
        return tmp

    def visit_LambdaExpr(self, node: LambdaExpr) -> str:
        # Create an anonymous function
        anon_name = self._builder.new_label("__lambda")
        fn_decl = FnDecl(
            span=node.span, name=anon_name,
            params=node.params, ret_type=node.ret_type,
            body=node.block or (BlockStmt(stmts=[
                __import__('lateralus_lang.ast_nodes', fromlist=['ReturnStmt'])
                .ReturnStmt(span=node.span, value=node.body)
            ]) if node.body else None),
            is_async=node.is_async
        )
        fn_decl.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.LOAD_STR, dest=tmp, src1=anon_name, span=node.span)
        return tmp

    def visit_ListExpr(self, node: ListExpr) -> str:
        tmps = [e.accept(self) for e in node.elements]
        tmp = self._builder.new_tmp()
        self._emit(IROp.MAKE_LIST, dest=tmp, src1=tmps,
                   src2=len(tmps), span=node.span)
        return tmp

    def visit_MapExpr(self, node: MapExpr) -> str:
        pairs = [(k.accept(self), v.accept(self)) for k, v in node.pairs]
        tmp = self._builder.new_tmp()
        self._emit(IROp.MAKE_MAP, dest=tmp, src1=pairs, span=node.span)
        return tmp

    def visit_AwaitExpr(self, node: AwaitExpr) -> str:
        val = node.value.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.AWAIT, dest=tmp, src1=val, span=node.span)
        return tmp

    def visit_CastExpr(self, node: CastExpr) -> str:
        val = node.value.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.CAST, dest=tmp, src1=val,
                   src2=str(node.target), span=node.span)
        return tmp

    def visit_MatchStmt(self, node: MatchStmt):
        subj_tmp    = node.subject.accept(self)
        after_label = self._builder.new_label("match_after")
        for arm in node.arms:
            next_label = self._builder.new_label("match_arm")
            pat_tmp = arm.pattern.accept(self)
            cmp_tmp = self._builder.new_tmp()
            self._emit(IROp.EQ, dest=cmp_tmp, src1=subj_tmp, src2=pat_tmp)
            self._emit(IROp.JF, dest=next_label, src1=cmp_tmp)
            if arm.body:
                arm.body.accept(self)
            elif arm.value:
                arm.value.accept(self)
            self._emit(IROp.JMP, dest=after_label)
            arm_bb = self._new_bb(next_label)
            self._current_bb = arm_bb
            self._emit(IROp.LABEL, dest=next_label)
        after_bb = self._new_bb(after_label)
        self._current_bb = after_bb
        self._emit(IROp.LABEL, dest=after_label)

    def generic_visit(self, node: Node):
        # Walk children for nodes not explicitly handled
        for val in vars(node).values():
            if isinstance(val, Node):
                val.accept(self)
            elif isinstance(val, list):
                for item in val:
                    if isinstance(item, Node):
                        item.accept(self)

    # ── v1.1 missing visitors ────────────────────────────────────────────────

    def visit_LoopStmt(self, node):
        body_label  = self._builder.new_label("lbody")
        after_label = self._builder.new_label("lafter")
        self._break_labels.append(after_label)
        self._continue_labels.append(body_label)
        self._emit(IROp.JMP, dest=body_label)
        body_bb = self._new_bb(body_label)
        self._current_bb = body_bb
        self._emit(IROp.LABEL, dest=body_label)
        node.body.accept(self)
        self._emit(IROp.JMP, dest=body_label)
        after_bb = self._new_bb(after_label)
        self._current_bb = after_bb
        self._emit(IROp.LABEL, dest=after_label)
        self._break_labels.pop()
        self._continue_labels.pop()

    def visit_InterpolatedStr(self, node) -> str:
        # Build by concatenating string parts with IR ADD
        result_tmp = self._builder.new_tmp()
        self._emit(IROp.LOAD_STR, dest=result_tmp, src1="", span=node.span)
        for kind, val in node.parts:
            if kind == "str":
                str_tmp = self._builder.new_tmp()
                self._emit(IROp.LOAD_STR, dest=str_tmp, src1=val, span=node.span)
                new_tmp = self._builder.new_tmp()
                self._emit(IROp.ADD, dest=new_tmp, src1=result_tmp,
                           src2=str_tmp, span=node.span)
                result_tmp = new_tmp
            # expr parts: we store as a comment (full parsing would require
            # re-lexing the fragment, which is deferred to the runtime)
        return result_tmp

    def visit_RangeExpr(self, node) -> str:
        start_tmp = node.start.accept(self)
        end_tmp   = node.end.accept(self)
        if node.inclusive:
            adj_tmp = self._builder.new_tmp()
            self._emit(IROp.ADD, dest=adj_tmp, src1=end_tmp, src2=1,
                       span=node.span)
            end_tmp = adj_tmp
        tmp = self._builder.new_tmp()
        self._emit(IROp.CALL, dest=tmp, src1="range",
                   src2=[start_tmp, end_tmp], span=node.span)
        return tmp

    def visit_TupleExpr(self, node) -> str:
        tmps = [e.accept(self) for e in node.elements]
        tmp  = self._builder.new_tmp()
        self._emit(IROp.MAKE_LIST, dest=tmp, src1=tmps,
                   src2=len(tmps), span=node.span)
        return tmp

    def visit_SelfExpr(self, node) -> str:
        tmp = self._builder.new_tmp()
        self._emit(IROp.SELF_REF, dest=tmp, span=node.span)
        return tmp

    def visit_StructLiteral(self, node) -> str:
        field_tmps = [(name, val.accept(self)) for name, val in node.fields]
        tmp = self._builder.new_tmp()
        self._emit(IROp.MAKE_STRUCT, dest=tmp, src1=node.name,
                   src2=field_tmps, span=node.span)
        return tmp

    def visit_StructDecl(self, node):
        fields_meta = [(f.name, str(f.type_) if f.type_ else "any")
                       for f in node.fields]
        self._emit(IROp.DEFINE_STRUCT, dest=node.name, src1=fields_meta,
                   span=node.span)
        self._scope.define(Symbol(name=node.name, kind="struct",
                                  type_="type", mutable=False))

    def visit_EnumDecl(self, node):
        variants_meta = [v.name for v in node.variants]
        self._emit(IROp.DEFINE_ENUM, dest=node.name, src1=variants_meta,
                   span=node.span)
        self._scope.define(Symbol(name=node.name, kind="enum",
                                  type_="type", mutable=False))

    def visit_TypeAlias(self, node):
        self._emit(IROp.TYPE_ALIAS, dest=node.name, src1=str(node.target),
                   span=node.span)
        self._scope.define(Symbol(name=node.name, kind="type_alias",
                                  type_=str(node.target), mutable=False))

    def visit_ImplBlock(self, node):
        # Emit each method as a named function prefixed with the type name
        for method in node.methods:
            qualified = FnDecl(
                span=method.span,
                name=f"{node.type_name}__{method.name}",
                params=method.params,
                ret_type=method.ret_type,
                body=method.body,
                is_async=method.is_async,
                is_pub=method.is_pub,
            )
            qualified.accept(self)

    def visit_InterfaceDecl(self, node):
        self._scope.define(Symbol(name=node.name, kind="interface",
                                  type_="type", mutable=False))

    def visit_YieldExpr(self, node) -> str:
        val = node.value.accept(self) if node.value else None
        tmp = self._builder.new_tmp()
        self._emit(IROp.YIELD_VAL, dest=tmp, src1=val, span=node.span)
        return tmp

    def visit_SpawnExpr(self, node) -> str:
        call_tmp = node.call.accept(self) if node.call else None
        tmp = self._builder.new_tmp()
        self._emit(IROp.SPAWN_TASK, dest=tmp, src1=call_tmp, span=node.span)
        return tmp

    def visit_ForeignBlock(self, node) -> str:
        """Emit a FOREIGN_CALL IR instruction for a polyglot block."""
        tmp = self._builder.new_tmp()
        # Evaluate param expressions so they are in scope
        param_tmps = {p.name: p.value.accept(self) for p in node.params}
        self._emit(
            IROp.FOREIGN_CALL,
            dest=tmp,
            extra={"lang": node.lang, "source": node.source, "params": param_tmps},
            span=node.span,
        )
        return tmp



    # ── v1.3 visitors ─────────────────────────────────────────────────────

    def visit_ThrowStmt(self, node) -> None:
        val = node.value.accept(self)
        self._emit(IROp.THROW, src1=val, span=node.span)

    def visit_EmitStmt(self, node) -> None:
        arg_tmps = [a.accept(self) for a in node.args]
        tmp = self._builder.new_tmp()
        self._emit(IROp.CALL, dest=tmp, src1="_bus.emit",
                   extra={"args": [repr(node.event)] + arg_tmps}, span=node.span)

    def visit_ProbeExpr(self, node) -> str:
        val = node.value.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.CALL, dest=tmp, src1="_probe", extra={"args": [val]}, span=node.span)
        return tmp

    def visit_MeasureBlock(self, node) -> None:
        t_start = self._builder.new_tmp()
        self._emit(IROp.CALL, dest=t_start, src1="_time.perf_counter", extra={"args": []}, span=node.span)
        node.body.accept(self)
        t_end = self._builder.new_tmp()
        self._emit(IROp.CALL, dest=t_end, src1="_time.perf_counter", extra={"args": []}, span=node.span)

    def visit_TryExpr(self, node) -> str:
        tmp = self._builder.new_tmp()
        # Simplified: treat like TryStmt but capture value
        node.body.accept(self)
        for clause in node.recoveries:
            clause.body.accept(self)
        if node.ensure:
            node.ensure.accept(self)
        return tmp

    # ── v1.4 visitors ─────────────────────────────────────────────────────

    def visit_ChainExpr(self, node) -> str:
        err = node.error.accept(self)
        cause = node.cause.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.CALL, dest=tmp, src1=f"{err}.caused_by",
                   extra={"args": [cause]}, span=node.span)
        return tmp

    def visit_PropagateExpr(self, node) -> str:
        val = node.value.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.CALL, dest=tmp, src1="_ltl_propagate",
                   extra={"args": [val]}, span=node.span)
        return tmp

    def visit_ComprehensionExpr(self, node) -> str:
        tmp = self._builder.new_tmp()
        iter_tmp = node.iter.accept(self)
        # Comprehensions are complex; for IR, emit a loop structure
        self._builder.new_tmp()  # placeholder
        return tmp

    def visit_GuardExpr(self, node) -> str:
        cond = node.condition.accept(self)
        tmp = self._builder.new_tmp()
        # guard is if-not-cond-then-fallback
        if hasattr(node, 'else_body') and node.else_body is not None:
            node.else_body.accept(self)
        return tmp

    def visit_WhereClause(self, node) -> str:
        node.bindings.accept(self)
        return node.expr.accept(self)

    def visit_PipelineAssign(self, node) -> None:
        val = node.value.accept(self)
        target = node.target.accept(self)
        self._emit(IROp.STORE, dest=target, src1=val, span=node.span)

    def visit_SpreadExpr(self, node) -> str:
        val = node.value.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.CALL, dest=tmp, src1="_spread", extra={"args": [val]}, span=node.span)
        return tmp

    def visit_TernaryExpr(self, node) -> str:
        cond = node.condition.accept(self)
        then_val = node.then_val.accept(self)
        else_val = node.else_val.accept(self)
        tmp = self._builder.new_tmp()
        self._emit(IROp.COND_SELECT, dest=tmp, src1=cond,
                   extra={"true": then_val, "false": else_val}, span=node.span)
        return tmp


# ─────────────────────────────────────────────────────────────────────────────
# Convenience
# ─────────────────────────────────────────────────────────────────────────────

def analyze(program, filename: str = "<unknown>") -> Tuple[IRModule, List[SemanticError]]:
    """Run semantic analysis and IR generation on an AST Program."""
    sa = SemanticAnalyzer(filename)
    module = sa.analyze(program)
    return module, sa.errors
